package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/thebrianlopez/runabout/cmd/workctl/internal/config"
	"github.com/thebrianlopez/runabout/cmd/workctl/internal/ui"
)

func initCmd() *cobra.Command {
	var force bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create a workctl config file at $XDG_CONFIG_HOME/workctl/config.yaml",
		Long: `Creates a template config file at the XDG config path.

The config file supports environment variable interpolation via ${VAR} syntax,
so credentials are never stored in plaintext.

Example config:
  atlassian:
    domain: ${ATLASSIAN_DOMAIN}
    token:  ${ATLASSIAN_API_TOKEN}`,
		RunE: func(cmd *cobra.Command, args []string) error {
			cfgDir := config.WorkctlConfigDir()
			cfgPath := cfgDir + "/config.yaml"

			if _, err := os.Stat(cfgPath); err == nil && !force {
				return fmt.Errorf("config already exists at %s\n  Use --force to overwrite", cfgPath)
			}

			if err := os.MkdirAll(cfgDir, 0o700); err != nil {
				return fmt.Errorf("creating config dir: %w", err)
			}

			template := `# workctl configuration
# Generated by: workctl init
# Reference:    https://github.com/blo-grindr/workctl

atlassian:
  domain: ${ATLASSIAN_DOMAIN}
  email:  ${ATLASSIAN_EMAIL}
  token:  ${ATLASSIAN_API_TOKEN}

github:
  token: ${GITHUB_TOKEN}
  user:  ""  # your GitHub username

defaults:
  timezone: America/Chicago
  format: md  # md|json|pdf — default for workflow subcommands (weekly/quarterly/review)
  confluence_type: page
  github_api: auto  # auto|events|search|graphql
  # github_repos: ""  # comma-separated repos for commit history (e.g. org/repo1,org/repo2)
  # github_enrich: false  # hydrate commits with per-file diff stats (slower)

# profiles:
#   # Workflow report profiles (use with workctl weekly/quarterly/review/reflect)
#   weekly-report:
#     email: "you@example.com"
#     github_user: "yourhandle"
#     format: md
#     summary: true
#
#   annual-review:
#     email: "you@example.com"
#     github_user: "yourhandle"
#     project_keys: "SR,ISRE"
#     space_keys: "ENG,INFRA"
#     since: 1y
#     format: md
#     summary: true
#
#   # Raw data query profiles
#   my-work:
#     email: "you@example.com"
#     github_user: "yourhandle"
#     github_repos: "myorg/myrepo1,myorg/myrepo2"
#     since: 30d
`
			if err := os.WriteFile(cfgPath, []byte(template), 0o600); err != nil {
				return fmt.Errorf("writing config: %w", err)
			}

			ui.Successf("Config written to: %s\n", cfgPath)
			fmt.Printf("   Set your GitHub username and add profiles, then run:\n")
			fmt.Printf("   workctl config validate\n")
			return nil
		},
	}

	cmd.Flags().BoolVar(&force, "force", false, "Overwrite existing config file")
	return cmd
}
